server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  datasource:
    username: root
    password: nacagawa1333

    url: jdbc:mysql://localhost:3306/letsbuy?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=true&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-circular-references: true

LetsBuy:
  jwt:
    secret: 'Algo aqui'
    expiration: 900000

azure:
  storage:
    account-key: //6vf+/Fci6X1ecJTMMzSHS+9cy/GvyXegw8VBbV3f+HFyn0JlXVvXDX8xSW8UQt2AvEtKOp1OJq+AStrWtzEw==
    blob-endpoint: https://letsbuy.blob.core.windows.net/images
    account-name: letsbuy