server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  datasource:
#    username: admin-trackio
#    password: '#Gfgrupo5'

    url: jdbc:sqlserver://srv-trackio.database.windows.net:1433;database=bd-letsbuy;user=admin-trackio@srv-trackio;password=#Gfgrupo5;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    testWhileIdle: true
    validationQuery: SELECT 1
  flyway:
    url: jdbc:sqlserver://srv-trackio.database.windows.net:1433;database=bd-letsbuy;user=admin-trackio@srv-trackio;password=#Gfgrupo5;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    locations: classpath:db/migration
    enabled: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-circular-references: true

LetsBuy:
  jwt:
    secret: 'Algo aqui'
    expiration: 900000

azure:
  storage:
    account-key: //6vf+/Fci6X1ecJTMMzSHS+9cy/GvyXegw8VBbV3f+HFyn0JlXVvXDX8xSW8UQt2AvEtKOp1OJq+AStrWtzEw==
    blob-endpoint: https://letsbuy.blob.core.windows.net/images
    account-name: letsbuy